recipemap('chemical_reactor').recipeBuilder()
    .inputs(ore('dustBauxite') * 5)
    .fluidInputs(liquid('sodium_hydroxide_solution') * 2000)
    .fluidOutputs(liquid('sodium_aluminate_solution') * 1000)
    .duration(150).EUt(7).buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
    .fluidInputs(liquid('water') * 3000)
    .fluidInputs(liquid('sodium_aluminate_solution') * 3000)
    .outputs(metaitem('dustAluminiumHydroxide') * 14)
    .fluidOutputs(liquid('sodium_hydroxide_solution') * 2000)
    .duration(150).EUt(7).buildAndRegister()

recipemap('electric_blast_furnace').recipeBuilder()
    .inputs(ore('dustAluminiumHydroxide') * 14)
    .outputs(metaitem('dustAlumina') * 5)
    .duration(320).EUt(30).buildAndRegister()

recipemap('electrolyzer').recipeBuilder()   
    .inputs(ore('dustAlumina') * 5)
    .inputs(ore('dustCarbon') * 3)
    .notConsumable(fluid('cryolite') * 288)
    .outputs(metaitem('ingotAluminium') * 4)
    .fluidOutputs(fluid('carbon_dioxide') * 3000)
    .duration(320).EUt(30).buildAndRegister()
