recipemap('chemical_reactor').recipeBuilder()
    .inputs(ore('dustSilicon') * 1)
    .fluidInputs(liquid('hydrochloric_acid') * 3000)
    .fluidOutputs(liquid('trichlorosilane') * 1000)
    .fluidOutputs(liquid('hydrogen') * 2000)
    .duration(160)
    .EUt(30)
    .buildAndRegister()
recipemap('chemical_reactor').recipeBuilder()
    .fluidInputs(liquid('trichlorosilane') * 1000)
    .fluidInputs(liquid('hydrogen') * 2000)
    .outputs(metaitem('dustSolarGradeSilicon') * 1)
    .fluidOutputs(liquid('hydrochloric_acid') * 3000)
    .duration(160)
    .EUt(30)
    .buildAndRegister()